{"name": "标识失败，结果为失败", "status": "skipped", "statusDetails": {"message": "XFAIL this test is expecting failure\n\nAssertionError: assert False", "trace": "self = <UI_Test_Project.test_case.test_07_allure_demo2.TestBaidu object at 0x00000206055DA488>\n\n    @allure.title(\"标识失败，结果为失败\")\n    @pytest.mark.xfail(ccondition=lambda: True, reason='this test is expecting failure')\n    def test_xfail_expected_failure(self):\n        \"\"\"被期望的失败\"\"\"\n>       assert False\nE       assert False\n\n..\\test_case\\test_07_allure_demo2.py:76: AssertionError"}, "description": "测试百度的搜索功能", "start": 1610786619956, "stop": 1610786619956, "uuid": "df443d61-235d-465a-b939-4444eb1d3ebd", "historyId": "ab33f7d0fa13497164a204ccf458b3f7", "testCaseId": "434b4149859c60e98a2ce11477a747b6", "fullName": "test_07_allure_demo2.TestBaidu#test_xfail_expected_failure", "labels": [{"name": "epic", "value": "百度"}, {"name": "feature", "value": "百度搜索"}, {"name": "severity", "value": "BLOCKER"}, {"name": "tag", "value": "mikezhou2"}, {"name": "tag", "value": "@pytest.mark.xfail(ccondition=<function TestBaidu.<lambda> at 0x0000020605507DC8>, reason='this test is expecting failure')"}, {"name": "suite", "value": "test_07_allure_demo2"}, {"name": "subSuite", "value": "TestBaidu"}, {"name": "host", "value": "LAPTOP-C73H3V04"}, {"name": "thread", "value": "14544-Thread-1"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_07_allure_demo2"}], "links": [{"type": "test_case", "url": "http://www.baidu.com", "name": "http://www.baidu.com"}]}